import React from "react";

export default function useGetFreelancerActiveJobs() {
  const activeJobs = [
    {
      id: 1,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
    {
      id: 2,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
    {
      id: 3,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
    {
      id: 4,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
    {
      id: 5,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
    {
      id: 6,
      title: "Video Editor",
      client: "TechBoost Media",
      status: "In Progress",
      skills: ["Adobe Premiere", "After Effects"],
      price: 200,
      jobId: "Job-2025-0123",
      startDate: "9/28/2025",
      endDate: "10/20/2025",
      agreement: "Contact.pdf",
    },
  ];

  return {activeJobs};
}
